# Country code to country name mapping for LegalTTSV2
# Format: 'CODE': 'Country Name',
COUNTRY_CODES = {
    'AU': 'Australia',
    'US': 'United States',
    'GB': 'United Kingdom',
    'CA': 'Canada',
    'NZ': 'New Zealand',
    'DE': 'Germany',
    'FR': 'France',
    'IN': 'India',
    'CN': 'China',
    'JP': 'Japan',
    'SG': 'Singapore',
    'ZA': 'South Africa',
    'IE': 'Ireland',
    'IT': 'Italy',
    'ES': 'Spain',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'RU': 'Russia',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'BE': 'Belgium',
    'NO': 'Norway',
    'FI': 'Finland',
    'DK': 'Denmark',
    'PL': 'Poland',
    'AT': 'Austria',
    'KR': 'South Korea',
    'TR': 'Turkey',
    'AR': 'Argentina',
    'CL': 'Chile',
    'PT': 'Portugal',
    'GR': 'Greece',
    'IL': 'Israel',
    'TH': 'Thailand',
    'MY': 'Malaysia',
    'ID': 'Indonesia',
    'PH': 'Philippines',
    'SA': 'Saudi Arabia',
    'AE': 'United Arab Emirates',
    'EG': 'Egypt',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'NG': 'Nigeria',
    'KE': 'Kenya',
    'GH': 'Ghana',
    'CO': 'Colombia',
    'VE': 'Venezuela',
    'CZ': 'Czech Republic',
    'HU': 'Hungary',
    'SK': 'Slovakia',
    'RO': 'Romania',
    'BG': 'Bulgaria',
    'HR': 'Croatia',
    'SI': 'Slovenia',
    'EE': 'Estonia',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'IS': 'Iceland',
    'MC': 'Monaco',
    'LI': 'Liechtenstein',
    'SM': 'San Marino',
    'VA': 'Vatican City',
    'QA': 'Qatar',
    'KW': 'Kuwait',
    'OM': 'Oman',
    'BH': 'Bahrain',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'PS': 'Palestine',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'SY': 'Syria',
    'YE': 'Yemen',
    'AF': 'Afghanistan',
    'NP': 'Nepal',
    'LK': 'Sri Lanka',
    'MM': 'Myanmar',
    'KH': 'Cambodia',
    'LA': 'Laos',
    'MN': 'Mongolia',
    'UZ': 'Uzbekistan',
    'KZ': 'Kazakhstan',
    'KG': 'Kyrgyzstan',
    'TJ': 'Tajikistan',
    'TM': 'Turkmenistan',
    'AZ': 'Azerbaijan',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'MD': 'Moldova',
    'BY': 'Belarus',
    'UA': 'Ukraine',
    'RS': 'Serbia',
    'ME': 'Montenegro',
    'MK': 'North Macedonia',
    'AL': 'Albania',
    'BA': 'Bosnia and Herzegovina',
    'XK': 'Kosovo',
    'ZW': 'Zimbabwe',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'SD': 'Sudan',
    'DZ': 'Algeria',
    'MA': 'Morocco',
    'TN': 'Tunisia',
    'LY': 'Libya',
    'SN': 'Senegal',
    'CM': 'Cameroon',
    'CI': 'Ivory Coast',
    'ET': 'Ethiopia',
    'AO': 'Angola',
    'MZ': 'Mozambique',
    'BW': 'Botswana',
    'NA': 'Namibia',
    'MG': 'Madagascar',
    'ZM': 'Zambia',
    'MW': 'Malawi',
    'LS': 'Lesotho',
    'SZ': 'Eswatini',
    'RW': 'Rwanda',
    'SL': 'Sierra Leone',
    'LR': 'Liberia',
    'GM': 'Gambia',
    'GW': 'Guinea-Bissau',
    'GN': 'Guinea',
    'ML': 'Mali',
    'BF': 'Burkina Faso',
    'NE': 'Niger',
    'TD': 'Chad',
    'CF': 'Central African Republic',
    'SS': 'South Sudan',
    'GA': 'Gabon',
    'CG': 'Congo',
    'CD': 'Democratic Republic of the Congo',
    'ST': 'Sao Tome and Principe',
    'GQ': 'Equatorial Guinea',
    'CV': 'Cape Verde',
    'SC': 'Seychelles',
    'MU': 'Mauritius',
    'KM': 'Comoros',
    'DJ': 'Djibouti',
    'SO': 'Somalia',
    'ER': 'Eritrea',
    'BJ': 'Benin',
    'TG': 'Togo',
    'MR': 'Mauritania',
    'EH': 'Western Sahara',
}
